#########Fixed and user-defined parameters################
metasheet: metasheet.csv  # Meta info 
ref: ref.yaml             # Reference config 
assembly: hg38
cancer_type: GBM          #TCGA cancer type abbreviations
rseqc_ref: house_keeping  #Option: 'house_keeping' or 'false'. 
                          #By default, a subset of housekeeping genes is used by RSeQC to assess alignment quality.  
                          #This reduces the amount of time needed to run RSeQC.  
mate: [1,2]               #paired-end fastq format, we recommend naming paired-end reads with _1.fq.gz and _2.fq.gz


#########Cohort level analysis parameters################
design: Group             # Condition on which to do comparsion (as set up in metasheet.csv)
Treatment: R              # Treatment use in DESeq2, corresponding to positive log fold change
Control: NR               # Control use in DESeq2, corresponding to negative log fold change
batch: syn_batch          # Options: 'false' or a column name from the metasheet.csv.  
                          # If set to a column name in the metasheet.csv, the column name will be used for batch effect analysis                                (limma).  
                          # It will also be used as a covariate for differential analysis (DESeq2) to account for batch effect.  

pre_treated: false        # Option: true or false. 
                          # If set to false, patients are treatment naive.  
                          # If set to true, patients have received some form of therapy prior to the current study.



############################################################
#                     list samples                         #
############################################################

samples:
  SRR8281218:
    - data/SRR8281218_1.fastq.gz
    - data/SRR8281218_2.fastq.gz
  SRR8281219:
    - data/SRR8281219_1.fastq.gz
    - data/SRR8281219_2.fastq.gz
  SRR8281226:
    - data/SRR8281226_1.fastq.gz
    - data/SRR8281226_2.fastq.gz
  SRR8281236:
    - data/SRR8281236_1.fastq.gz
    - data/SRR8281236_2.fastq.gz
  SRR8281230:
    - data/SRR8281230_1.fastq.gz
    - data/SRR8281230_2.fastq.gz
  SRR8281233:
    - data/SRR8281233_1.fastq.gz
    - data/SRR8281233_2.fastq.gz
  SRR8281244:
    - data/SRR8281244_1.fastq.gz
    - data/SRR8281244_2.fastq.gz
  SRR8281245:
    - data/SRR8281245_1.fastq.gz
    - data/SRR8281245_2.fastq.gz
  SRR8281243:
    - data/SRR8281243_1.fastq.gz
    - data/SRR8281243_2.fastq.gz
  SRR8281251:
    - data/SRR8281251_1.fastq.gz
    - data/SRR8281251_2.fastq.gz
  SRR8281238:
    - data/SRR8281238_1.fastq.gz
    - data/SRR8281238_2.fastq.gz
  SRR8281250:
    - data/SRR8281250_1.fastq.gz
    - data/SRR8281250_2.fastq.gz

############################################################
#                    Neoantigen testing                    #
############################################################

